<?php

$files = [ 'Optional'
         , 'Absent'
         , 'Present'
         , 'Collection'
         , 'FlArray'
         , 'Text'
         , 'Number'
         , 'SQLException'
         , 'Entity'
         , 'Util'
         , 'entity/CompraImportadaProdutoNovo'
         , 'entity/Transportador'
         , 'entity/OrdemDeProducao'
         , 'entity/brindart/OrdemDeProducao'
         , 'entity/ClienteCreditoInfo'
         , 'entity/Destinatario'
         , 'entity/FinanceiroContaProgramada'
         , 'entity/FinanceiroContaProgramadaConta'
         , 'entity/FinanceiroContaProgramadaBaixa'
         , 'entity/Fornecedor'
         , 'entity/Fornecedor2'
         , 'entity/Produto'
         , 'entity/Produto2'
         , 'entity/ProdutoFornecedor'
         , 'model/CompraImportadaXml'
         , 'model/CompraImportadaXmlItem'
         , 'model/CompraImportadaStatus'
         , 'model/CompraImportadaStatusItem'
         , 'model/CompraNovo'
         , 'model/CompraItemNovo'
         , 'model/PedidoItemComDesconto'
         , 'loader/Transportador'
         , 'ponto/Day'
         , 'ponto/Interval'
         , 'ponto/Util'
         , 'util/Financeiro'
         , 'dateTime/DateTimeUtil'
         , 'ViewHelper' ];

forEach($files as $file)
  require_once __DIR__ . '/' . $file . '.php';
